[mypy]
plugins = mypy_django_plugin.main,
          mypy_drf_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = test_project.settings

[mypy-*.migrations.*]
ignore_errors = True

[mypy_django_plugin]
ignore_missing_model_attributes = True

[mypy-graphene.*]
ignore_missing_imports = True

[mypy-autoslug.*]
ignore_missing_imports = True

[mypy-ajax_select.*]
ignore_missing_imports = True

[mypy-dbdiff.*]
ignore_missing_imports = True